apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-access
spec:
  podSelector:
    matchLabels:
      app: postgres-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ecom-go-api
          podSelector:
            matchLabels:
              app: ecom-go-api
      ports:
        - protocol: TCP
          port: 5432
