image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

postgresUser: postgres
postgresPassword: postgres123
postgresDb: go_ecom

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

resources: {}
