name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Go test
        run: go test ./...

      - name: Build docker image
        run: docker build -t ecom-api:ci .
